name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/you2apidocker
          registry: docker.io
          tags: latest
          multiPlatform: true
          platform: linux/amd64,linux/arm64,linux/arm/v7
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
